#!/bin/bash
set -e

psql --username "$POSTGRES_USER" --dbname "$FG_DB_NAME" \
  -v app_user="$FG_DB_APP_USER" <<-EOSQL

ALTER DEFAULT PRIVILEGES FOR ROLE :"app_user"
IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO :"app_user";

ALTER DEFAULT PRIVILEGES FOR ROLE :"app_user"
IN SCHEMA public
GRANT USAGE, SELECT, UPDATE
ON SEQUENCES TO :"app_user";

ALTER DEFAULT PRIVILEGES FOR ROLE :"app_user"
IN SCHEMA public
GRANT EXECUTE
ON FUNCTIONS TO :"app_user";

EOSQL
